name: Desert Sky Rangers Website CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  DSR_GPG_PASSWORD: ${{ secrets.DSR_GPG_PASSWORD }}
  ACM_MAVEN_REPO_USERNAME: ${{ secrets.ACM_MAVEN_REPO_USERNAME }}
  ACM_MAVEN_REPO_PASSWORD: ${{ secrets.ACM_MAVEN_REPO_PASSWORD }}
  ACM_XENON_REPO_USERNAME: ${{ secrets.ACM_XENON_REPO_USERNAME }}
  ACM_XENON_REPO_PASSWORD: ${{ secrets.ACM_XENON_REPO_PASSWORD }}

  DISPLAY: ":99"
  GITHUB_REF: ${{ github.ref }}
  JAVA_VERSION: "21"
  MAVEN_PARMS: "-B -U -V --settings .github/settings.xml --file pom.xml"
  NODE_VERSION: "22"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

  WEBSITE_DEPLOY_PATH: '/opt/dsr/web/www.desertskyrangers.org/'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v6

      - name: Fetch CI/CD resources
        uses: actions/checkout@v6
        with:
          repository: desertskyrangers/cicd
          path: .github

      - name: Configuration
        shell: bash
        run: |
          source .github/config.sh

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test:ci

      - name: Package
        run: |
          cd dist
          zip -r ../client.zip *

      - name: Deploy
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: |
          ssh -t ${{env.ACM_XENON_REPO_USERNAME}}@desertskyrangers.org "mkdir -p ${{env.WEBSITE_DEPLOY_PATH}};" 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
          scp -r -B dist/* ${{env.ACM_XENON_REPO_USERNAME}}@desertskyrangers.org:${{env.WEBSITE_DEPLOY_PATH}} 2>&1
          if [ $? -ne 0 ]; then exit 1; fi
